kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: blue-green-route
  annotations:
    haproxy.router.openshift.io/balance: random
spec:
  to:
    kind: Service
    name: user14-hello-chart
    weight: 100
  alternateBackends:
  - kind: Service
    name: user14-hello-world
    weight: 0