ReplicaNumber: 1

containers:
  containerPort: 8080
  image: 'quay.io/yuri_rshtunique/myimage'
  tag: 'v7'

service:
  servicePort: 8080

#new section
probes:
  readiness:
    path: /health/readiness # this check the application url path
    initialDelaySeconds: 1 # the time is waiting befor testing the application path
    timeoutSeconds: 1 # the time for timeout
    periodSeconds: 10 # the abount of time to wait between checks
    successThreshold: 1 # count to decalre seccessfull 
    failureThreshold: 3 # count to decalre failure
  liveness:
    path: /health/readiness # this check the application url path
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3 

volume:
  mount:
    path: /tmp/html # this will mount the html.index file to it application location

test: HealD

github:
  user: yuri_rshtunique
  token:  
  url: https://api.github.com/repos/yuri_rshtunique/Day1/issues